### ISSUE TITLE
When you click on an active workflow you see: "Running: 4 of 5 tasks completed" This sort of implies that the entire workflow only has one more task to do- but this is just showing done and active tasks.

### ISSUE THREAD

**Issue by hjfbynara** [DataBiosphere/job-manager#267]
The "Running:" line only shows the tasks that are either running or completed - but the workflow may have many more tasks that have yet to be launched.  So a message of: "Running: 4 of 5 tasks completed" could imply that the workflow is almost done.  But if the workflow may have dozens of tasks yet to be started - the message "4 of 5 tasks completed" kind of gives a false impression.

Is it possible to query the metadata or cromwell - to give you real total of tasks.  It may not be possible especially if there are some kind of conditionals or if scatter is data driven.  Maybe alternatively change in the wording of the message to remove the implication - just state what you know.

Tasks: 4 completed; 1 running; 0 failed

**Comment by kbergin** [comment]
Hi @hjfbynara thank you for filing this! I just noticed this today myself. Definitely very misleading. I will file a ticket to improve the wording here. I think, as you suspected, it is not possible for us to know how many tasks a workflow will have before they actually start. I will confirm this with cromwell team.

**Comment by rsasch** [comment]
@kbergin @hjfbynara What are the statuses that are worth summarizing here (current options: submitted, on hold, running, aborting, failed, succeeded, and aborted)? And if "completed" is one, would it include "failed" and "succeeded"?

**Comment by rsasch** [comment]
*Blocked*: need specifics on which task statuses are pertinent and worth showing.

**Comment by cjllanwarne** [comment]
I think the underlying problem here is that Cromwell *does not list* tasks that haven't been started yet - so you'll never see a task in some "not even thought about yet" state.

I think the best thing to do here is say "4 tasks complete, 1 task currently being processed"

**Comment by kbergin** [comment]
Yes seconding what Chris said. We can't give the information the user really wants, so what we should convey is what we do know in an accurate way. 

The way Chris phrased it sounds great

**Comment by ruchim** [comment]
+1 Chris!

**Comment by rsasch** [comment]
@kbergin @hjfbynara There was a suggestion in the associated PR that the language distinguish between "completed successfully" and "completed failingly", so what do you think of this language:

> Tasks: 3 succeeded, 1 failed, 1 currently being processed

**Comment by kbergin** [comment]
That looks great, bec! Thank you!
