### ISSUE TITLE
Have a repeatable release process

### ISSUE THREAD

**Issue by cjllanwarne** [DataBiosphere/job-manager#313]
- [ ] A process (preferably automated, or else at least documented) to create releases of JMUI
- [ ] Run through it at least once to produce a release that we can point people to (even if still an 'alpha' release)
- [ ] Turn on "Releases" on github to mark release hashes and allow us to point to the appropriate artifacts.

**Comment by cjllanwarne** [comment]
NB @rexwangcc performed the most recent release and that insight will be invaluable while documenting and/or automating this process.

**Comment by rexwangcc** [comment]
^ I believe so?

**Comment by ruchim** [comment]
@rsasch I'm closing this issue -- but feel free to re-open as needed.
