### ISSUE TITLE
Deployment in a hosted environment

### ISSUE THREAD

**Issue by cjllanwarne** [DataBiosphere/job-manager#314]
- Probably depends on a released version existing (#313)
- Document HOWTO and any gotchas setting up JMUI to run in the hosted environment
  - Can be super-specific to GAE, Kubernetes, ??? for now - whatever makes the most sense
- The more that deployment can be automated, the better!

**Comment by cjllanwarne** [comment]
Note: @rexwangcchas already made a lot of progress on this.

Also note the script here https://github.com/HumanCellAtlas/secondary-analysis/blob/master/deploy/job-manager/deploy.sh which it might be possible to co-opt

**Comment by rexwangcc** [comment]
Breaking this into #327, #328, #329 and #330
