### ISSUE TITLE
Deployment on a local (personal) machine

### ISSUE THREAD

**Issue by cjllanwarne** [DataBiosphere/job-manager#315]
- Probably depends on a released version existing (#313)
- Document HOWTO and any gotchas setting up JMUI to run on a local machine
  - Can be super-specific to Mac, some *nix flavor, (Windows!?) for now ... whatever makes the most sense
- The closer this process can be to a single line `"type this command into your terminal and wait for the setup to complete"`, the better.
- Ideally after setup the user would end up with a single command to bring up and down the locally hosted JMUI

**Comment by cjllanwarne** [comment]
@rexwangcc is this the same as ticket 297 in elastc? Should I mark you as "assigned" to this?

**Comment by cjllanwarne** [comment]
Great, thanks!

I'm a big fan of small tactical PRs so if it makes sense, feel free to break this issue into two (or more!) separate issues, eg one "what you were already planning to do for 297" and one "everything else, to be done later"

**Comment by rexwangcc** [comment]
That sounds practical, will do it!

**Comment by rexwangcc** [comment]
Breaking this into #327 and #330
