### ISSUE TITLE
Configurable List View

### ISSUE THREAD

**Issue by cjllanwarne** [DataBiosphere/job-manager#319]
~~@kbergin, @rsasch, @ruchim: could you add a quick description of what "Configurable List View" means to you in Q3?~~

From elastc issue 301:

---

As a user of a job manager where it is used by anyone besides myself, I want to be able to set the labels that I see in the list view based on what I find the most useful or based on what my project uses (in the case of JMUI aaS). The label options will be from a set of best practice suggestions (white list), although a user could use other labels and see them on the details view. 

AC:
- [x] User can select (in UI) up to 5 columns to view in list view from white list
- [x] User can set order of columns preferably by drag and drop but if that's difficult than another method works.
- [x] JMUI remembers the columns they want to see when they return
- [ ] Any columns they have in view are options for filtering

![15_columnsettings_5ad1160090bddf04e8fd3e40_207112933149202157168_5132_](https://user-images.githubusercontent.com/13006282/42525839-36f08eb2-8442-11e8-86fd-3575e8d5e2f7.png)

**Comment by kbergin** [comment]
@cjllanwarne https://elastc.com/c/vHHUknxz/301-configure-list-view-labels-in-ui contains the description. Could we consider using the existing tickets to create new ones here, as the content is all there in elastc already.

**Comment by cjllanwarne** [comment]
Thanks @kbergin - I've copied the content here (is that what you had in mind when you said "using the existing tickets to create new ones here"?)

**Comment by ruchim** [comment]
@rsasch -- what's left to complete in this issue? Seems like the functionality already exists.

**Comment by rsasch** [comment]
@ruchim The last checkbox, "Any columns they have in view are options for filtering," hasn't been completed, because:
 - label columns can't be both editable and filterable
 - there's no user story for filtering by `status` or date-based columns (submission, start, end)

**Comment by ruchim** [comment]
@rsasch -- I tried filtering by status in the query bar and it worked, and same for submission/start/end.

I think it's okay if one can't filter by editable filters for now -- I'll file it as a separate issue since the last thing in the AC that's incomplete, and the feature around configuring columns in JMUI is complete, so I'd like to close this issue.
