### ISSUE TITLE
Deployment documentation for Kubernetes

### ISSUE THREAD

**Issue by rexwangcc** [DataBiosphere/job-manager#328]
Document HOWTO and any gotchas setting up JMUI to run on a Kubernetes cluster, which provides high availability for production use cases. (derived from #314 and #315)

Ideally, this should cover:

- descriptions for each necessary config file
- descriptions for each necessary environment variable
- template yaml files for creating deployment, service and ingress
- a minimal readme

## Checklist
- [x] Cromwell
~dsub~

**Comment by rexwangcc** [comment]
https://github.com/DataBiosphere/job-manager/pull/326 should address this.

**Comment by ruchim** [comment]
Since @rexwangcc has already addressed this need, closing the issue.
