### ISSUE TITLE
Implement State in JMUI

### ISSUE THREAD

**Issue by kbergin** [DataBiosphere/job-manager#335]
This doc explains why the the job manager requires state https://docs.google.com/document/d/11szRUroEWm2-5hTluB9S7XkTjqusr9zqPai6TJWFoqw/edit

A technical decision was made at the end of that document to implement state through browser local storage as a first pass. "Persist settings in browser local storage. This persists across browser sessions, but has no association with a user’s identity across machines (possible extension for Chrome: sync across profiles)." For more detail see document.

AC:
A new release of job manager with browser local storage capabilities
Preferably works in all job managers (locally deployed, k8s, app engine, hosted, etc)

**Comment by rsasch** [comment]
closed for realsies this time (hopefully)!
