### ISSUE TITLE
Support clickable label filters on the table view

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#340]
![image](https://user-images.githubusercontent.com/14941133/42712709-a5b5471e-86ba-11e8-9b3c-4096fab8e3d3.png)

As a user, I want to be able to quickly filter by a label that's on a job I'm looking at. See attached wireframe.

**Comment by rsasch** [comment]
How does this work with the current functionality where clicking on a label value allows users to edit that value?

**Comment by rsasch** [comment]
@ruchim This currently works for all `text` fields that aren't `editable`.  Does that satisfy this requirement?

**Comment by ruchim** [comment]
@rsasch I think its great that the filtering works for fields that aren't editable!

As a suggestion, for something like Labels -- is it possible to do both filter on a value as is, and the option to edit it?

**Comment by rsasch** [comment]
@ruchim It's possible, but we don't have a user experience/design for how this would look/happen.

**Comment by ruchim** [comment]
Closing as these changes have been merged to v0.5.1 and above.
