### ISSUE TITLE
Remove client side subworkflow filtering

### ISSUE THREAD

**Issue by kbergin** [DataBiosphere/job-manager#359]
Cromwell 33 supports excluding subworkflows from the query results. Currently, we are receiving pages of query results and then filtering out the subworkflows client side. When many workflows with subworkflows are returned, they will slow down and potentially crash the job manager. This fix enables more robustness, scale, and speed in the JMUI.

AC:
- [x] Remove client side filtering of subworkflows and start excluding subworkflows by default in the query to Cromwell API. 

Note that in the future we hope to enable the user to configure if they want to see subworkflows in the list view, so we should implement this in a way that it can be toggled on or off by the user. This ticket could be done before we do the configurable UI work, but let me know if it is not a good idea to do that.

From another ticket:
Now with Cromwell version 33, we can query for only parent workflows and do pagination properly.
- added `includeSubworkflows` set to `false` in query to Cromwell backend
- re-worked the way the shim layer for Cromwell uses page tokens
- added additional UI tests for pagination

**NB**: we still need a fix for Cromwell not returning the correct `totalResultsCount` value when subworkflows are excluded.

See https://elastc.com/c/C46fjeNX/320-bug-when-there-s-only-one-page-it-still-says-of-many

**Comment by kbergin** [comment]
@gemmalam @rsasch this is the ticket I thought corresponded with the PR I accidentally closed. How do we link the PR with this issue?

**Comment by gemmalam** [comment]
@kbergin there's a "connect with an issue" button on the bottom of every PR if you have the Zenhub extension. Let me know if you aren't seeing it. I just connected it.

**Comment by rsasch** [comment]
Fixed when PR #312 was merged
