### ISSUE TITLE
Update filtering by date to new UX

### ISSUE THREAD

**Issue by kbergin** [DataBiosphere/job-manager#382]
Marty shared some new filtering by dates UX wireframes to help us out. Update Query Builder to new UX; https://docs.google.com/presentation/d/1XybPRjNfUn6JtaQJbn2k6cXZQs-BervMCY5uKAxx-3Y/edit#slide=id.g2662c45064_0_22

AC:
Implemented date picker UX update

![image.png](https://images.zenhubusercontent.com/5a9f2a304b5806bc2bc9b485/ce7e62ee-2725-4dfb-96b5-18291c389c39)

**Comment by rsasch** [comment]
@ruchim Is this a separate issue from #440?

**Comment by rsasch** [comment]
closed in favor of #440
