### ISSUE TITLE
Handle submitted cromwell workflows gracefully

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#390]
When jobs are submitted to cromwell, they do not have metadata immediately. It's possible that the new submit and hold feature of cromwell will cover this, but currently our job manager will show 'empty' looking jobs until they actually start in cromwell, due to the metadata not being available. If the update to the submit and hold feature will not solve this problem for all cromwell types (hosted, caas, local, sge) then we will need a way to handle this in the UI. 

AC:
Blank looking jobs aren't shown to users by default until they either are active, fail, or complete
Users *could* see them if they want to

**Comment by rsasch** [comment]
@ruchim Does the addition of the 'on hold' status and the ability to make the job name not the first column resolve this issue?

**Comment by ruchim** [comment]
Absolutely it does, closing this issue.
