### ISSUE TITLE
Resources tab of subworkflow pages

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#396]
Resource tabs of subworkflow pages are not clear. Maybe when we move to collapsible subworkflows this won't be an issue?

<img width="1267" alt="screen shot 2018-07-27 at 4 31 10 pm" src="https://user-images.githubusercontent.com/14941133/43345194-87dedc36-91ba-11e8-99b3-6b9480adc4f9.png">

**Comment by rsasch** [comment]
@ruchim Would be addressed by #535 ?

**Comment by ruchim** [comment]
Does the list of inputs for subworkflows still include a UUID? It seems buggy that inputs include a UUID at all, and that seems like a parsing issue?

**Comment by rsasch** [comment]
@ruchim Can you provide an example of what you mean by UUID?  Should this be a separate issue?

**Comment by ruchim** [comment]
1. In the example above, the first input is a UUID and the second is `increase_disk_size` -- I'm surprised the first UUID is a real input? Maybe there's a bug there? I guess it's impossible to confirm without the actual workflow...

2. Is it possible to get a screenshot of what the inputs/outputs look like after being collapsed with  task list/graph view? The example in the PR shows a before and after of the task list: https://github.com/DataBiosphere/job-manager/pull/543
Would love the same before and after for inputs/outputs tab.

**Comment by rsasch** [comment]
@ruchim Can you check to see if this is still an issue? I don't have access to the workflow cited above, so I can't check the metadata to see if inputs and outputs are being displayed correctly.

**Comment by ruchim** [comment]
We're good!

**Comment by ruchim** [comment]
<img width="1416" alt="Screen Shot 2019-04-18 at 10 59 21 PM" src="https://user-images.githubusercontent.com/14941133/56403042-b28ac500-622d-11e9-9838-668b84f4fb7b.png">
Proof
