### ISSUE TITLE
Show task level inputs/outputs

### ISSUE THREAD

**Issue by kbergin** [DataBiosphere/job-manager#410]
I can only see inputs and outputs for the workflow as a whole. It would be helpful to be able to see inputs and outputs for each task and also for subworkflows.

Was submitted in elastc by @dshiga

**Comment by rsasch** [comment]
@kbergin Would this be resolved by #535 (PR is #543)?

**Comment by ruchim** [comment]
In Terra, without this information in Job Manager, users have no way to know which inputs were used by a call/task, especially when they’re not explicit file types, such as ints/strings being used to define runtime resources. 

This can be critical when debugging, if an input string was misspelled or an int was incorrectly calculated. A user would need to directly access the API to get this information.
