### ISSUE TITLE
Subworkflow links should be router links

### ISSUE THREAD

**Issue by kbergin** [DataBiosphere/job-manager#434]
@samanehsan FYI; I ( @calbach )  noticed that clicking a subworkflow resulted in a full page load, which is going to be a lot slower than using a routerLink. See https://github.com/DataBiosphere/job-manager/blob/master/ui/src/app/job-list/table/table.component.html#L38

This would become irrelevant if we move to collapsible subworkflows and no longer have a separate details page.

**Comment by rsasch** [comment]
@kbergin Was this addressed by #540?

**Comment by kbergin** [comment]
I'm not sure, @rsasch . I think this was something that is an implementation detail that I'm not familiar with, I think I was making the ticket for @calbach

**Comment by calbach** [comment]
I don't know where the subworkflow link is if it still exists. If that button still exists and clicking that refreshes the whole page, then the bug still exists.

**Comment by rsasch** [comment]
@calbach Here is the call to the `router` that I was referring to in that PR: https://github.com/DataBiosphere/job-manager/pull/540/files#diff-28e7af551c1526a3e1844c2c1727b115R61

**Comment by rsasch** [comment]
Resolved by #540
