### ISSUE TITLE
Handle Cromwell outage more gracefully

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#442]
Today, trying to navigate to the caas dev job manager resulted in a plain text page that just said 500 server error. This was due to problems in CaaS (which were in turn due to problems in Sam).

The user experience could be improved. We could show a custom error page with a more user friendly message. Or we could show the regular job manager landing page and just leave the jobs table empty, with a message saying that we're having trouble talking to CaaS.

**Comment by cjllanwarne** [comment]
I think there's a whole class of "make initial connections easier to set up" since this is closely related to my experience in #441
