### ISSUE TITLE
Submitted job shows negative duration

### ISSUE THREAD

**Issue by samanehsan** [DataBiosphere/job-manager#468]
When viewing the details page of a job with the status "Submitted", I noticed the duration was negative. I expected it to be empty or 0, since the job is not running yet: 

![screen shot 2018-08-27 at 2 10 46 pm](https://user-images.githubusercontent.com/6414394/44677123-2a884e80-aa03-11e8-8c2f-651e6b7a15fc.png)

**Comment by ruchim** [comment]
@rsasch this might be a nice bug to fix after archiving is complete?
