### ISSUE TITLE
Total job count doesn't refresh when you change filter

### ISSUE THREAD

**Issue by kbergin** [DataBiosphere/job-manager#476]
Small thing we noticed today. We have two project ids we're filtering on that are very similar at first glance but have different time stamps. If we filter by the first one, ending in 45Z, it shows 996 total workflows and displays those workflows in the list view. 

![image](https://user-images.githubusercontent.com/9449764/45493019-c02e1880-b73b-11e8-8367-bed474a407e7.png)

When I change the filter to the other time stamp, ending in 55Z and click enter, it refreshes the list of filtered workflows but not the total number of workflows for the pagination.
![image](https://user-images.githubusercontent.com/9449764/45493088-f8cdf200-b73b-11e8-865d-151847cf7e30.png)
![image](https://user-images.githubusercontent.com/9449764/45493101-fff50000-b73b-11e8-87be-48a8a69bcc75.png)

If I refresh the page, there are actually 999 total workflows that match that filter
![image](https://user-images.githubusercontent.com/9449764/45493114-0be0c200-b73c-11e8-8885-0e76f3d77c03.png)

If I x out the filter chip entirely, the same bug is observed. It still says 999 workflows even though there are 3649 after I refresh the page.
![image](https://user-images.githubusercontent.com/9449764/45493144-1bf8a180-b73c-11e8-952d-8323b41447d7.png)
![image](https://user-images.githubusercontent.com/9449764/45493165-261aa000-b73c-11e8-9468-f27a4471f2a5.png)

**Comment by dshiga** [comment]
When the total is incorrect, hovering over the "next page" arrow causes it to update.

**Comment by rsasch** [comment]
@calbach I tried reinstantiating the paginator, although I might not have tried to do so in the right place.  I found that in order to reproduce the issue, you need to have the query (both the original and then the filtered one) return more than 100 jobs.  Were you able to test with that many?

**Comment by calbach** [comment]
Thanks, I just tested with 500 and wasn't able to reproduce. Granted this was on the dsub backend which doesn't return a totalSize so the codepaths might be slightly different here.

**Comment by calbach** [comment]
I see - in this case it's probably set correctly. It's not exhaustive. I think it was just never updated to account for the `totalLength` changes. I would just drop that if check.

**Comment by calbach** [comment]
Also - nice find
