### ISSUE TITLE
Google Auth should use the appropriate Google account for bucket links

### ISSUE THREAD

**Issue by dinvlad** [DataBiosphere/job-manager#486]
I'm not sure of the best way to handle this, but currently if we click on a bucket link in the UI, it always uses the first user logged in in the browser, so the console UI displays a 403 if that user doesn't have access to the bucket.

When GCP console handles this in Console UI, they use `authuser=x` param in all links. I think it should be possible to use that here as well, based on the list of logged in users on the client.

**Comment by dinvlad** [comment]
Hi Ruchi - the use case is rather simple: when I run Job Manager from a personal computer, I usually use a browser where I'm logged in as both my personal GMail account and institutional (Broad). Usually my personal account is the first in the list of Google accounts in the browser, so that results in broken links.

Additionally, I noticed that even when I'm logged in with just the Broad account, I still get 403 on stdout and stderr links. Only "task call folder" links work for me then.

Thanks!

**Comment by ruchim** [comment]
Hey @dinvlad ,

Thats interesting, when you log into Job Manager -- whatever that user account is should be used when redirecting a user to logs. To test this theory, would you mind running Job manager from an incognito window and confirming that even when you're just logged in with your Broad account, can you see the logs or not? 

Thanks

**Comment by dinvlad** [comment]
Hi @ruchim,

Even when I'm logged in in incognito just with my Broad account, I _cannot_ see the logs - only a 403.

I think Google Cloud Storage Browser adds something to their requests that's not normally present in the URL. If I navigate to a folder in the Storage Browser and copy a file link (in the form [1]), then paste it in a new tab, it has the same form as the link from Job Manager, and _also_ displays a 403. However, when instead click on the link, then it displays the file successfully. So the Storage Browser UI must be "decorating" the "click" event with some further information that's not present in the copied URL (I think this may be the user token or a signature of the URL), which is why we also can't use it from Job Manager without adding that extra bit.

Perhaps @lukwam has some insight into this?

Thanks!

[1] `https://storage.cloud.google.com/<executions_bucket>/workflows/<workflow_name>/<workflow_id>/call-<task_name>/<file_name>?_ga=2.xxxxxxxxx.-yyyyyyyyyyy.zzzzzzzzzz`

**Comment by calbach** [comment]
Agreed chrome profiles generally behave better or equally well as multilogin across most products. That said, we should fix this bug as multilogin is pretty common and we should not make assumptions/requirements around chrome profiles or primary vs secondary account usage.

I can take this issue since we have the same bug right now in Workbench. It looks like a straightforward fix. Note: this fix will only work if your configuration of Job Manager requires you to sign in @dinvlad.

**Comment by dinvlad** [comment]
Thanks @calbach (and @lukwam), I think there are actually 2 separate issues - one as reported first in this issue (wrt. multi-login), and the second as reported in https://github.com/DataBiosphere/job-manager/issues/486#issuecomment-435235743, namely that currently Job Manager _stdout_/_stderr_ links are broken altogether - even when I use a single account and chrome profile!

**Comment by calbach** [comment]
Indeed that sounds like it's probably a separate issue. Perhaps @rsasch can help debug that one as she's better equipped to repro issues that only show up in the Cromwell-backed UI.
