### ISSUE TITLE
Changing the icons for Job Manager

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#517]
Context: Based on usability testing for Job Manager, it seems the current icons used to represent status don't easily link to workflow status for many users.

Marty has recommended icon changes as follows:
![submitted](https://user-images.githubusercontent.com/14941133/48575040-e0668900-e8de-11e8-9666-b2e57cc925a0.png) <-- Submitted

![onhold](https://user-images.githubusercontent.com/14941133/48575046-e52b3d00-e8de-11e8-838e-0e23e8e20468.png) <-- On hold

![runaborting](https://user-images.githubusercontent.com/14941133/48575054-ea888780-e8de-11e8-9f98-b3713f80b5e3.png) <-- Running, Aborting

![failed](https://user-images.githubusercontent.com/14941133/48575061-efe5d200-e8de-11e8-8b9c-f3c0e154e147.png) <-- Failed

![aborted](https://user-images.githubusercontent.com/14941133/48575065-f411ef80-e8de-11e8-8e12-db11b35d0d9a.png) <-- Aborted

![succeeded](https://user-images.githubusercontent.com/14941133/48575072-f83e0d00-e8de-11e8-86ca-4952677a3fea.png) <-- Succeeded

**Comment by rexwangcc** [comment]
Thanks for the heads up! (The icons for failed and aborted are still a little bit confusing to me from a user perspective.)
