### ISSUE TITLE
Status options for quick filtering

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#518]
Today on Job Manager, the quick filters exist for statuses.

- Active = Running
- Completed = Aborted & Succeeded
- On Hold = On Hold

Usability testing shows that:
1. The term "Completed" was very confusing and not easy to associate with statuses Succeeded and/or Aborted.
2. It was hard to make the link when the quick filters have a different name than the actual status.

To ease those concerns, it may be best to make the association between status & quick filters more obvious by displaying each of the most prominent statuses as its own quick filter:

For example, a quick filter called "Running" to show all workflows in "Running" status. And the same for Succeeded, Failed, Aborted & On Hold.

**Comment by rsasch** [comment]
A request was made by users to add the status icon to the buttons for extra clarity.
