### ISSUE TITLE
Add hashbang to quickstart script

### ISSUE THREAD

**Issue by morgantaschuk** [DataBiosphere/job-manager#526]
Hi! I got this set up and talking to our Cromwell install today. Nice work on the docs.

One suggestion for an enhancement: can you put a hashbang at the top of the jmui_start.sh script? I couldn't get it running in systemd until I added `#!/usr/bin/env bash` to the top of that script.

**Comment by ruchim** [comment]
Seems like a reasonable request :) Thanks for the suggestion!

**Comment by rsasch** [comment]
@morgantaschuk Thank you for your feedback. This fix is now available in the [v0.5.0](https://github.com/DataBiosphere/job-manager/releases/tag/v0.5.0) release.
