### ISSUE TITLE
Improve display of workflows that fail before starting

### ISSUE THREAD

**Issue by pshapiro4broad** [DataBiosphere/job-manager#529]
If a workflow fails due to a WDL or input error, the Job Manager shows a blank space where the workflow name would normally be. The blank space looks odd to me and removes an area that could be interacted with (e.g. to bring up the workflow details view).

![image](https://user-images.githubusercontent.com/1799360/49386786-5136df00-f6ee-11e8-897d-de28dce6ffac.png)

Also, there is no way to view these kind of errors in the Job Manager. When I click on Job Details the page only contains the submitted, started and ended times.

![image](https://user-images.githubusercontent.com/1799360/49387470-e5557600-f6ef-11e8-8758-af4b89488846.png)

For the name, maybe `Unknown` or `Not Started` or the workflow ID would be a good fallback.

For the errors, the details page could include the data in the top level `failures` metadata property, either directly or inside a disclosure element.

**Comment by ruchim** [comment]
Hey @pshapiro4broad,

We're planning on swapping out the primary column to be workflow ID -- which is always guaranteed to be present. In that case, would you still want the workflow name to contain a placeholder value?

As for the failure, you're right we should be able to grab it from metadata.

**Comment by rsasch** [comment]
The [v0.5.1](https://github.com/DataBiosphere/job-manager/releases/tag/v0.5.1) version of Job Manager supports being able to re-order the columns in the job list view.
