### ISSUE TITLE
Show less generic message when a subworkflow has failed

### ISSUE THREAD

**Issue by rsasch** [DataBiosphere/job-manager#533]
Right now, if a subworkflow of a task fails in Cromwell, all that is shown in the error messages tab is ''Workflow failed" which is not useful.  There are more specific error messages returned by the `/metadata` endpoint, so the most helpful error message should be returned.

**Comment by rsasch** [comment]
@ruchim In the UI, this will result with an error message being displayed in a list, with each item having icons for stdout, stderr and execution directory.  But, since this message is from a subworkflow, the metadata doesn't provide links to these, so they will be greyed out or missing.  Will this be helpful or frustrating for the user?

e.g.

<img width="1558" alt="screen shot 2018-12-11 at 11 28 43 am" src="https://user-images.githubusercontent.com/1713505/49814894-8b306280-fd38-11e8-85ae-bb3884a92fc8.png">

**Comment by ruchim** [comment]
I think this is an improvement on what was there before! 

Is there anyway to parse metadata twice for this, and find stdout/stderr for a task named "submit"?

**Comment by rsasch** [comment]
@ruchim Looking at the metadata, the shim layer would have to parse the beginning of the error message to see if it can pull out a sub-workflow name ("submit"), walk through the `calls` section to find the corresponding sub-workflow ID and then make a new metadata request to get the `stderr`, `stdout` and `callRoot`.  Is it possible Cromwell could eventually include more details besides `"message"` in the `failures` array so this could all be done with one metadata request?

**Comment by rsasch** [comment]
@ruchim If I'm missing another way to get this info from the metadata, please correct me.

**Comment by rsasch** [comment]
Without the ability to add the log and execution directory links, this doesn't actually save the user any steps.

**Comment by ruchim** [comment]
@rsasch sorry for realizing this late, but in this particular type of error mode, there would be no links to stdout/stderr or call directory as this task seems to fail before anything can actually run. This error should totally be displayed even without the links, and possibly a different way to show those types of errors in the UI.

**Comment by rsasch** [comment]
I think the above situation is covered by #588.
