### ISSUE TITLE
Health check for cromwell backend

### ISSUE THREAD

**Issue by danbills** [DataBiosphere/job-manager#551]
As a developer, it'd be nice to know whether the job manager api is able to communicate with a backend cromwell.

This could take the form of the following:

• a health check endpoint returns != 200
• api manager exits with a failure when connection fails

Either one of these behaviors would allow Kubernetes to keep restarting the api backend until Cromwell was ready to be accessed.

**Comment by cjllanwarne** [comment]
Closed by #554
