### ISSUE TITLE
Timing Diagram sometimes looks weird 

### ISSUE THREAD

**Issue by rexwangcc** [DataBiosphere/job-manager#566]
The (text of )Timing Diagram sometimes looks weird when you first click into the "Timing Diagram" tab, as it shown below. It however seems to be able to fix itself if you refresh the page and click into the tab again:

![screen shot 2019-02-19 at 10 23 30 pm](https://user-images.githubusercontent.com/14366016/53064345-79381200-3495-11e9-82ff-f94488fe6161.png)

**Comment by rsasch** [comment]
One of the changes in https://github.com/DataBiosphere/job-manager/pull/564, which adds events, only shows the event/task/subworkflow name and other details on mouseover, which is much cleaner.

**Comment by rexwangcc** [comment]
Ah I see! Thanks, a strong reason to take a look at that PR 😸

**Comment by rsasch** [comment]
@rexwangcc Now that the above PR has been merged, can this issue be closed?

**Comment by rexwangcc** [comment]
Addressed!
