### ISSUE TITLE
Job Manager list view falls over with invalid queries

### ISSUE THREAD

**Issue by rsasch** [DataBiosphere/job-manager#569]
Job Manager will error and look to be endlessly loading (if the user clicks on the "Dismiss" link) if the user enters an invalid query. 

![screen shot 2019-02-25 at 5 27 07 pm](https://user-images.githubusercontent.com/1713505/53373141-af0c4900-3922-11e9-9fa4-e459ed973e55.png)

**Comment by cjllanwarne** [comment]
Is that a valid workflow name? I'm pretty sure WDL won't allow anything non-alphanumeric-or-dash

**Comment by rsasch** [comment]
But does it make sense for the UI to enforce this?  What are the restrictions for CWL?

**Comment by ruchim** [comment]
I do agree that it's probably for Cromwell to enforce and could move to the Cromwell repo. @cjllanwarne any objections?
