### ISSUE TITLE
Docker compose setup -- break out mysql? 

### ISSUE THREAD

**Issue by zfrenchee** [DataBiosphere/job-manager#578]
Job Manager supports dsub and cromwell backends. When Job Manager uses cromwell as a backend, it deploys [a cromwell container](https://github.com/DataBiosphere/job-manager/blob/8ddd4ec3d5c2861e066b5d4a9b6965291dceb30b/cromwell-instance-compose.yml#L14-L22) in the compose setup. Cromwell also documents how to set up a compose setup in their [docs](https://cromwell.readthedocs.io/en/stable/Configuring/#database) and there, they split out mysql and cromwell containers:

https://github.com/broadinstitute/cromwell/blob/673cc21bd7f649ff2c1b37c896a5b55afc1ba557/scripts/docker-compose-mysql/docker-compose.yml#L2-L22

Should Job Manager also have a container for mysql in the compose file?

**Comment by rsasch** [comment]
The "cromwell" container in Job Manager does not contain an instance of Cromwell, it is the python shim layer that makes API calls to a Cromwell.

**Comment by zfrenchee** [comment]
Thanks!
