### ISSUE TITLE
Get shard status from latest attempt

### ISSUE THREAD

**Issue by rsasch** [DataBiosphere/job-manager#590]
Currently, Job Manager shows an inaccurate status, duration and timing diagram for scattered tasks when a shard (or shards) has more than 1 attempt.

**Comment by rsasch** [comment]
@ruchim Does it make sense to show attempts for a scattered task? e.g.

<img width="759" alt="Screen Shot 2019-03-15 at 10 07 04 AM" src="https://user-images.githubusercontent.com/1713505/54437275-a9787680-470a-11e9-8b72-fa71f30f04d4.png">

If so, is it the total number of attempts across all shards?

**Comment by ruchim** [comment]
I would say this is the total number of unique shards -- so showing a summary of the latest attempts of all shards
