### ISSUE TITLE
Move labels to a tab (ie inputs) on job details page 

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#599]
Today, there are some labels that take up prime real estate on the workflow details page...

<img width="1197" alt="Screen Shot 2019-03-20 at 2 33 21 PM" src="https://user-images.githubusercontent.com/14941133/54710138-6ad52880-4b1d-11e9-84f8-a3ec8758384a.png">

Motivation: 
Instead of them being open at all times, as they're not always needed for debugging and can take up a huge portion of the page. We want that information to continue being available, just taking up less of the space, and so the decision to move it to a tab. Hoping to replace that open space with more workflow-level information (such as link to the execution directory, call caching enabled/disabled, so on)

**Comment by rsasch** [comment]
@ruchim Where in the order of the tabs should it go?  Current order (when applicable) is:

1. List View
2. Errors
3. Inputs
4. Outputs
5. Timing Diagram

**Comment by rsasch** [comment]
@ruchim Please confirm:
- order will be
1. List View
2. Errors
3. Inputs
4. Outputs
5. Labels
6. Timing Diagram

- whether or not a label is displayed at the top of the Job Details page will be configurable in the capabilities file; default is to show at the top

**Comment by rsasch** [comment]
After off-line discussion with @ruchim – the labels shown at the top will be the same as the columns shown in the list view.  If the user elects to hide a column in the list view, that will move that label from the top of the job details page to the "Labels" tab.
