### ISSUE TITLE
Update the Job Manager's Favicon

### ISSUE THREAD

**Issue by rexwangcc** [DataBiosphere/job-manager#600]
https://github.com/DataBiosphere/job-manager/blob/master/ui/src/favicon.ico the favicon of Job Manager is still the default "Angular CLI ICON". This is true for all of the JMUI instances that I have access to (caas, local, Terra). It will be great to have JMUI's customized favicon!!

**Comment by ruchim** [comment]
Agreed! Let's change it to a green hexagonal JM so that it aligns more properly with Terra icon.

**Comment by ruchim** [comment]
https://github.com/DataBiosphere/terra-landing/blob/master/favicon.png#boards
