### ISSUE TITLE
Fix stderr/stdout paths

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#602]
Today, when using Job Manager through Terra and clicking on the stdout/stderr links -- the redirect brings one to the correct file path -- but the file is treated like a directory, as the error says "There are no live objects in this folder".

<img width="1335" alt="Screen Shot 2019-03-22 at 9 59 22 AM" src="https://user-images.githubusercontent.com/14941133/54828076-c7555680-4c89-11e9-98d6-4b242e2a7e2e.png">

And when I traverse the directory structure one level up, I see the actual execution directory, which includes a link to the stdout/stderr files.
<img width="1334" alt="Screen Shot 2019-03-22 at 10 05 03 AM" src="https://user-images.githubusercontent.com/14941133/54828221-17ccb400-4c8a-11e9-8e28-fa3cb0071312.png">

AC: 
1. Correct the links to the stderr/stdout files as objects, instead of folders.
2. Ensure the redirect links open the new URLs in a new tab, instead of the existing one.
3. Add tests to make sure these behaviors (#1 and #2) don't regress in the future, as these links are crucial to debugging.

**Comment by rsasch** [comment]
@ruchim Is this happening with all Cromwell jobs or just a particular kind of job/task?

**Comment by ruchim** [comment]
I believe all -- I've been able to reproduce it pretty consistently on the the various links I've tried.

**Comment by rsasch** [comment]
Can you replicate this with jobs that were not run via Terra?

**Comment by ruchim** [comment]
happy to test on a local JM together!
