### ISSUE TITLE
Display Workflow failure message from /metadata

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#603]
There can be various kind of failure modes and some of them are not captured in the stderr/stdout logs.

For those cases, the Cromwell workflow metadata under the key "failure" is the best source of information. Here's an example of a workflow that can be debugged in FireCloud based on using the information from metadata:
![image](https://user-images.githubusercontent.com/14941133/54846472-55ddce00-4cb2-11e9-9227-bb38d1b787bb.png)

**Comment by rsasch** [comment]
Can you explain how this is not covered by #533 and/or #588 ?

**Comment by ruchim** [comment]
Hey @rsasch -- I believe #588 is about missing workflow details for workflow that don't exist in Cromwell, leaving no way to display them. In this issue, the workflow has a UUID so there is information Cromwell has that can be displayed, it's just not making it to the Job Manager UI.

Quite similar to #533 -- and I've updated some thoughts on that issue. Let's catch up on this --because I believe there's a reproducible case to show that there are failure exceptions shown in Cromwell metadata but possibly getting swallowed by the UI -- so just want to make sure that's not the case.

**Comment by ruchim** [comment]
@rsasch Just want to be sure that you clarified this feature is actually mostly in -- we simply need to change the task name to something like "Workflow Error"

**Comment by rsasch** [comment]
This is where the "task name" should be changed in the case of workflow-level failure: https://github.com/DataBiosphere/job-manager/blob/master/servers/cromwell/jobs/controllers/jobs_controller.py#L226
