### ISSUE TITLE
Stylize the tab icon for JMUI

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#611]
<img width="567" alt="Screen Shot 2019-03-27 at 12 18 26 PM" src="https://user-images.githubusercontent.com/14941133/55093269-83e45900-508a-11e9-8c5d-87350e5fa567.png">

There's a logo on the tab that looks like a red "A" for Job Manager -- let's change it to hexagonal JM so that it aligns more properly with Terra.

**Comment by rsasch** [comment]
@ruchim duplicate of #600 ?

**Comment by ruchim** [comment]
yes, im a duplication master.
