### ISSUE TITLE
displaying workflow errors

### ISSUE THREAD

**Issue by dvoet** [DataBiosphere/job-manager#614]
when I click on a failed workflow the following screen has a box that looks like

![image](https://user-images.githubusercontent.com/1521333/55179829-b6f81c80-515e-11e9-81f8-987568a36163.png)

Hovering over the triangle with ! icon displays error text. The fact that this is hover text is problematic as it is impossible to copy/paste it. It is also really hidden. How do I know to hover over that icon? When my code fails don't want to have to hunt for the error message.

**Comment by ruchim** [comment]
@dvoet 

Two things -- 
1. It's hidden -- and so changing that by changing its color to be red, so one is more likely to hover over it. https://github.com/DataBiosphere/job-manager/issues/634
2. There is an "errors" tab where one can copy/paste text they want to travel with them. 

Closing this as I think we addressed both facets, but re-open if you find the solution insufficient.
