### ISSUE TITLE
Automatic Sign out

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#623]
From the perspective of clinically compliant software, Job Manager needs to be able to log users out of the application along with their Google account after 5 minutes of idle activity.

**Comment by aednichols** [comment]
- How do we create a timer in Angular?
- How do we reset that timer to zero upon activity? Every single click? Lots of code places to change.
- Should we have a "1 minute left" popup to warn users? Most software with a forced logout seems to have such a thing.
- How do we force a sign out of the Google account - we do know of a "token revoke" curl command
  - All signouts - manual and automatic - should be "hard" in the sense that the Google account is also signed out
- Does this apply to all users? Filter by email domain?

**Comment by aednichols** [comment]
I dug up the revoke curl, it is `curl https://accounts.google.com/o/oauth2/revoke?token={token}`

**Comment by aednichols** [comment]
>A common misconception, which some vendors perpetuate, is that software can be CLIA-certified. Certainly a vendor that conducts its own sequencing with clinical samples can claim that its software has been used in a CLIA-compliant lab—but once that software is used outside of that lab, such claims are irrelevant. CLIA applies to lab processes and is a certification given to a lab and its workflows, not to the specific instruments, software, and other technology the lab uses. [1]

- Nuking a user's Google identity in the browser does nothing to remove access via e.g. gsutil CLI
- One off-the-cuff solution - have the lab auto-lock their workstations after 5 minutes. Way less disruptive than sign-out, blocks gsutil access, and might already be in place as a corporate IT policy

[1] https://www.coreinformatics.com/blog/clia-certified-lims/

**Comment by aednichols** [comment]
- Add a key like `"forced_logout_domains"` to the `"authentication": { ...}` section in `capabilities.json`
  - Points to an array of strings that's a list of the domains

**Comment by ruchim** [comment]
User Flow:

- A user logs in 
- If the user is in a specific domain (list specified in the config), then a timer goes off in the background (time specified in the config) to keep track of idle time*
- As there are 10 seconds left to the idle timeout -- a banner pops up saying "you will be logged out due to inactivity"
- If the user does any mouse/keyboard actions, then the timer is re-set to the idle timeout. Else, the user is logged out *and* their token is revoked.

*idle time = a user isn't using the mouse or the keyboard. this excludes things like the UI could be taking a while to load a page -- so the timer *after* API calls finish. 

Requirements:
- Make the list of domain names configurable
- Make the length of the idle timeout configurable
