### ISSUE TITLE
Timing Diagram error

### ISSUE THREAD

**Issue by cjllanwarne** [DataBiosphere/job-manager#637]
The Cromwell metadata for tasks can look funky following a restart. In one situation this has led to an unusable timing diagram:

<img width="860" alt="Screen Shot 2019-05-03 at 8 46 43 AM" src="https://user-images.githubusercontent.com/13006282/57138290-486f3580-6d80-11e9-823f-182c003bc130.png">

We should investigate:
- Is the metadata good, but because it contains a restart Job Manager is interpreting it incorrectly?
  - If so, Job Manager should be resilient to it
- Is the metadata trash following the restart?
  - If so, Cromwell should guarantee good metadata even after a restart
  - Job Manager could try to do "as much as it can", though I admit the definition of this is very tricky without trying to guess all the ways that the metadata could be messed up.

**Comment by rsasch** [comment]
Need the metadata in question in order to investigate.

**Comment by aednichols** [comment]
@vdauwera saw the same:

<img width="1261" alt="Screen Shot 2019-05-15 at 12 56 21 AM" src="https://user-images.githubusercontent.com/1087943/57736013-815ab480-7674-11e9-8fc3-e83d2867a7c6.png">

and it went away on its own:

>huh now I get a normal timing diagram -- is it possible this resolved itself by getting updated metadata? it was a running workflow

We asked her to check her system clock and she reported it was about 30 seconds slow.

My theory is that a `now()` timestamp generated on a client with a slow clock is somehow conflicting with an accurate time generated by the server.

**Comment by cjllanwarne** [comment]
Or alternatively, a new metadata appeared overriding the "finish" time, thus moving it ahead of the recently added "start" time?

**Comment by vdauwera** [comment]
This would be a great place for a typo since “Finnish time” is exactly what I’m on...

**Comment by rsasch** [comment]
should be addressed by https://github.com/DataBiosphere/job-manager/pull/656
