### ISSUE TITLE
Status and log file links fail to display in Firefox

### ISSUE THREAD

**Issue by aednichols** [DataBiosphere/job-manager#639]
It's not a tracking protection thing either, FF reports no blockable content on the page.

![Screen Shot 2019-05-03 at 4 55 38 PM](https://user-images.githubusercontent.com/1087943/57165202-68284d00-6dc4-11e9-984e-88321fd459fc.png)

![Screen Shot 2019-05-03 at 4 55 26 PM](https://user-images.githubusercontent.com/1087943/57165201-68284d00-6dc4-11e9-949b-e66dc3b16ad0.png)

**Comment by rsasch** [comment]
Looks like all clarity icons are gone – the 'X' at the top right...etc.
