### ISSUE TITLE
Abort button on the job details page

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#646]
Today: there is an option to abort jobs from the list view.

AC: Add the ability to abort jobs from the workflow details page, via a button, with the same downstream flow as the case in the list view.

**A user with "write" permissions on a jobs:**
1. Someone click on a button to abort a running job/workflow -->
2. A pop up asks the user to confirm they want to --> 
3. Abort signal sent to Cromwell --> 
4. The page refreshes in a few seconds so that the new "Aborting" status registers on the page

**A user without "write" permissions on a jobs:**
1. Someone click on a button to abort a running job/workflow -->
2. A pop up asks the user to confirm they want to --> 
3. Abort signal sent to Cromwell --> 
4. Abort signal failed to send and Job Manager reports an error that says "You don't seem to have the permissions to abort jobs." 

This will only appear at the top level Job Details page, not for sub-workflows.

**Comment by ruchim** [comment]
<img width="1288" alt="Screen Shot 2019-05-10 at 11 24 29 AM" src="https://user-images.githubusercontent.com/14941133/57538458-73283380-7316-11e9-9dd8-2ac90f5d5f78.png">

**Comment by rsasch** [comment]
see https://github.com/DataBiosphere/job-manager/pull/657
