### ISSUE TITLE
Buggy behavior when expanding 1 shard

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/job-manager#653]
For a scattered sub-workflow -- if there's only 1 shard -- expanding it for details just fails.

AC: If this is still a bug, ensure that rendering expansion on a single shard (be it scattered task or sub-workflow) succeeds.

Ask @dinvlad if cannot be reproduced, as he may have a good case for this.

**Comment by rsasch** [comment]
@dinvlad @ruchim The behavior for shards is different in the case of a sub-workflow or a task.

- If it's a task, the shard row is expandable to show all the attempts (you will also see a 
![Screen Shot 2019-05-23 at 4 13 23 PM](https://user-images.githubusercontent.com/1713505/58283200-b4d4c780-7d75-11e9-8232-95e2533f9163.png) at the end of its row).
- If it's a sub-workflow, the rows are not expandable, but the shard name (e.g. "shard 0") is a link that will take you to the details of that shard.

Please let me know if I misunderstood the underlying issue.

**Comment by dinvlad** [comment]
@rsasch - I think the behavior affects task shard as you mentioned. The problem is that when there's only shard-0, if I click the down arrow, it doesn't show the expansion (or maybe it shows, but the expanded row gets hidden behind the border). I think it might have miscalculated the row height.

**Comment by dinvlad** [comment]
Here’s what I see when expanding the sole shard: 
![CF1C9CB2-3506-4C37-8DF8-361F2FFF773B](https://user-images.githubusercontent.com/137337/58297199-e749e900-7da4-11e9-9a49-b3dde26234f9.jpeg)

**Comment by gemmalam** [comment]
@dinvlad I've moved this issue to our new Jira board. Let me know if you have any issues accessing it! https://broadworkbench.atlassian.net/browse/BA-5648
