### ISSUE TITLE
Automatically redirect to https

### ISSUE THREAD

**Issue by samanehsan** [DataBiosphere/job-manager#658]
Reported by @kislyuk, if you log into the Cromwell-as-a-Service job manger using the http url instead of https, you will get an error and cannot log in. Instead, the page should re-direct to https to avoid any confusion.
 
![image](https://user-images.githubusercontent.com/6414394/60359795-12c58200-99a8-11e9-99ad-ab3b2ab37ea2.png)

**Comment by gemmalam** [comment]
Hi @samanehsan! Our board is currently living in Jira now. I will close this issue in favor of the new one I created for you in Jira. Thank you! https://broadworkbench.atlassian.net/browse/BA-5776
